### ISSUE TITLE
Client class does not offer proper means of closing its resources

### ISSUE THREAD

**Issue by rpatel-figure** [provenance-io/p8e-scope-sdk#59]
## Summary of Issue
`io.provenance.scope.sdk.Client` has a `io.provenance.scope.sdk.SharedClient` value that needs to be closed after it is done being used:
https://github.com/provenance-io/p8e-scope-sdk/blob/868f44014656273f74f5dab5135f0977c19f710c/sdk/src/main/kotlin/io/provenance/scope/sdk/Client.kt#L114
While said value is currently public and is technically able to be closed currently via
```kotlin
val someClient = Client(someSharedClient, someAffiliate)

// Code here which uses someClient

someClient.inner.close()
if (someClient.inner.awaitTermination(someDuration) {
    // Proceed
}
```
it would be more desirable if the `Client` class implemented `java.io.Closeable` (and optionally also provided the `awaitTermination` function) so that one could do
```kotlin
val someClient = Client(someSharedClient, someAffiliate)

// Code here which uses someClient

someClient.close()
if (someClient.awaitTermination(someDuration) {
    // Proceed
}
```
This seems to be a better practice to give confidence that all the resources used by the class are being properly closed both now or in a future where `Client` has other values which implement `Closeable`, and is a practice already followed by `SharedClient`:
https://github.com/provenance-io/p8e-scope-sdk/blob/3b96a4c2cc2c4537725f691379c8bdbd4a188a01/sdk/src/main/kotlin/io/provenance/scope/sdk/Client.kt#L91-L93
It also allows usage of Kotlin's `Closeable.use` to concisely ensure resources are closed even if an exception is thrown.

## Version

3b96a4c2cc2c4537725f691379c8bdbd4a188a01 (Sole relevant file last updated in 868f44014656273f74f5dab5135f0977c19f710c)

## Steps to Reproduce
For any instance of the `Client` class called `someClient`, execute `someClient.execute(...)` without eventually calling `someClient.inner.close()` to observe a stacktrace like the following
```
*~*~*~ Channel ManagedChannelImpl{logId=61, target=object-store-v2.p8e:80} was not shutdown properly!!! ~*~*~*
p8e-cee-api-deployment-8679879c5b-jhvxb p8e-cee-api     Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
p8e-cee-api-deployment-8679879c5b-jhvxb p8e-cee-api java.lang.RuntimeException: ManagedChannel allocation site
p8e-cee-api-deployment-8679879c5b-jhvxb p8e-cee-api 	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
p8e-cee-api-deployment-8679879c5b-jhvxb p8e-cee-api 	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
p8e-cee-api-deployment-8679879c5b-jhvxb p8e-cee-api 	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
p8e-cee-api-deployment-8679879c5b-jhvxb p8e-cee-api 	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
p8e-cee-api-deployment-8679879c5b-jhvxb p8e-cee-api 	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
p8e-cee-api-deployment-8679879c5b-jhvxb p8e-cee-api 	at io.provenance.scope.objectstore.client.OsClient.<init>(OsClient.kt:80)
p8e-cee-api-deployment-8679879c5b-jhvxb p8e-cee-api 	at io.provenance.scope.sdk.SharedClient.<init>(Client.kt:77)
```
with the `target` in the first line referencing the value of `someClient.inner.config.osGrpcUrl`.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rpatel-figure** [comment]
Would be happy to address this myself if anyone agrees with this

**Comment by rpatel-figure** [comment]
Released in https://github.com/provenance-io/p8e-scope-sdk/releases/tag/v0.6.1
